### ISSUE TITLE
Can't unset BlockSeenStory

### ISSUE THREAD

**Issue by RJVB** [ducng99/InstagramPP#1]
The default setting to block the story seen status means I get the same stories served again and again, so I want it off for me.

Problem is, I can't get it to remain off via the settings page. Untick the box, click "save", reload the page and the option is on again. Fortunately this is a userscript so I can hack the code to set the variable to off instead of reading it from settings storage but I'm a bit afraid that I will have forgotten that I need to do this by the time the script is auto-updated.

Using Firefox Dev. Edition (up-to-date) and Tampermonkey (up-to-date) on Linux but I've seen the same issue with Chromium and Tampermonkey on Mac (both up-to-date too).

**Comment by ducng99** [comment]
Apologies for the super late reply.
This is now fixed, was an issue with deploying configuration page.

**Comment by RJVB** [comment]
>This is now fixed, was an issue with deploying configuration page.

Thanks, I'll check!

**Comment by ducng99** [comment]
And make sure to have the latest version (>= 4.8.2), as it is now future-proof to changes in config page (it won't break).

**Comment by RJVB** [comment]
It doesn't seem to be auto-updating in TamperMonkey?

**Comment by ducng99** [comment]
You can force an update by going to Tampermonkey's Dashboard and click the time in "Last updated" column
![image](https://github.com/ducng99/InstagramPP/assets/49080794/adcf82a1-3c80-43a1-a3a8-5c0d19084e0e)

Or just reinstall the script, that definately works

**Comment by RJVB** [comment]
Wow, thanks, that's almost intuitive :)

For some reason the update didn't work in a single browser only, so no biggie.
